version: '3.6'

services:
  perico2:
    image: borabora/perico2
    container_name: perico2
    privileged: true
    volumes:
      - ./volumes/perico2/voices:/usr/src/app/voices
      - ./.env:/usr/src/app/.env
    ports:
      - "9051:9051"
